hwi_oauth:
    http_client:
        verify_peer: false
    connect:
        account_connector: appbundle.oauth.user_provider
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebookId
    resource_owners:
        facebook:
            type: facebook
            client_id: %oauth.facebook.id%
            client_secret: %oauth.facebook.secret%
            scope:         "email, public_profile, user_birthday"
            infos_url:     "https://graph.facebook.com/me?fields=id,email,first_name,last_name,gender,birthday"