# JMS Payment Configuration
jms_payment_core:
    secret: S3ecr3tK3yP4ssw0rd

# JMS Paypal Payment Configuration
jms_payment_paypal:
    username: looktubefrance-facilitator_api1.gmail.com
    password: 4BQC573ELMRMBG4R
    signature: AzFxqZicLf23KXC0ytTWQe9l0zXzAusvrzyTtJUq7CnkSq0icerdDIiu
    debug: true

# JMS DI Configuration
jms_di_extra:
    locations:
        all_bundles: false
        bundles: AppBundle
        directories: ["%kernel.root_dir%/../src"]
    automatic_controller_injections:
        properties:
            request: "@request"
            router: "@router"
        method_calls:
            setRouter: ["@router"]